# Generated by Django 5.1.3 on 2024-12-02 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='viewed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
