# Generated by Django 5.1.3 on 2024-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngreList',
            fields=[
                ('ingre_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingre_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IngreLocDict',
            fields=[
                ('ingre_loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategoryDict',
            fields=[
                ('recipe_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_category_name', models.CharField(max_length=20)),
            ],
        ),
    ]
