# Generated by Django 5.1.3 on 2024-12-01 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_amount', models.IntegerField()),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_level', models.IntegerField()),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeThumbSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_src', models.CharField(max_length=255)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_time', models.IntegerField()),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeVideoSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_src', models.CharField(blank=True, max_length=255, null=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('recipe_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.recipecategorydict')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'recipe_category'), name='unique_recipe_category')],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_amount_lst', models.CharField(max_length=50)),
                ('ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ingrelist')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'ingre'), name='unique_recipe_ingre')],
            },
        ),
        migrations.CreateModel(
            name='RecipeMainIngre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_ingre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ingrelist')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'main_ingre'), name='unique_recipe_main_ingre')],
            },
        ),
        migrations.CreateModel(
            name='RecipeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_progress', models.CharField(max_length=255)),
                ('recipe_img_src', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe', 'recipe_progress'), name='unique_recipe_progress'), models.UniqueConstraint(fields=('recipe', 'recipe_img_src'), name='unique_recipe_img_src_per_recipe')],
            },
        ),
    ]
